
title: THInK Team
email: boris.vaisband@uci.edu
description: >
  At THInK Team, we focus on enabling heterogeneous integration of systems. 
  We deep dive into fine-pitch integration platforms and generate design methodologies, circuits, 
  and EDA tools to increase system performance, reduce energy footprint, and enable novel applications.
# baseurl: ""
url: "https://thinkteam.github.io"
baseurl: ""

twitter_username: "" # TODO
github_username:  "https://github.com/THInK-Team"

# Build settings
markdown: kramdown
theme: "uswds-jekyll"
styles:
  - /assets/main.css
sass:
    sass_dir: _sass
gems:
  - jekyll-feed
exclude:
  - node_modules
  - package.json
  - Gemfile
  - Gemfile.lock
  - README.md
  - docs/*
  - _members/template.md
  - _projects/project-template.md
  - _themes/project-name.md
  - _news/yyyy-mm-dd-template.md
  - .travis.yml
  - vendor

collections:
  projects:
    output: true
    permalink: /research/:collection/:path/
  themes:
    output: true
    permalink: /research/:path/
  members:
    output: true
    permalink: /team/:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  positions:
    output: true
    permalink: /team/:collection/:path/
  news:
    output: true
    permalink: /:collection/:path/
  teams:
    output: true
    permalink: /research/:collection/:path/
defaults:
  - scope:
      path: ""
      type: publications
    values:
      layout: publication
  - scope:
      path: ""
      type: news
    values:
      layout: news
  - scope:
      path: ""
      type: projects
    values:
      layout: project
  - scope:
      path: ""
      type: positions
    values:
      layout: position
  - scope:
      path: ""
      type: members
    values:
      layout: member
  - scope:
      path: ""
      type: themes
    values:
      layout: theme
  - scope:
      path: ""
      type: teams
    values:
      layout: team
